### PR TITLE
ACES 1.0.2 config

### PR DESCRIPTION
**Pull request by hpd**
Contributors:
@hpd
@KelSolaar
@selfshadow
@KevinJW
https://github.com/hpd/OpenColorIO-Configs/graphs/contributors

The jump from the 1.0.1 config to the 1.0.2 only reflects the tagging of the ACES 1.0.1 + hotfixes commits as the ACES 1.0.2 release. The OCIO config has not changed otherwise.

Copied into this branch from
https://github.com/hpd/OpenColorIO-Configs/tree/a69bb04267b43154a0b12bcb20c1c9ed21c12558
Look to that fork for the full commit history of this config.

### CODE REVIEW

**Comment by scoopxyz** [comment]
Looping back on this. Is this pull request useful / desired by anyone (due to the release of 1.0.3)? Or should we proceed to mark this as deprecated / abandonded?

**Comment by KelSolaar** [comment]
From an historical perspective I think I would merge it, it gives a comparison basis. @hpd and Alex Fry were doing such things a few weeks ago.

**Comment by scoopxyz** [comment]
I tend to agree, it certainly doesn't hurt anything to provide the "intermediary" version.

**Comment by aforsythe** [comment]
For the sake of clarity there should be a config for each ACES release.  Even if one is labeled 1.0.2 / 1.0.3.  Productions won’t be aware of the differences or lack there of of.

Alex


On January 12, 2017 at 3:57:03 PM, Sean Cooper (notifications@github.com) wrote:
> I tend to agree, it certainly doesn't hurt anything to provide the "intermediary" version.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/imageworks/OpenColorIO-Configs/pull/9#issuecomment-272321968

[?]<http://www.oscars.org>


Alex Forsythe
Image Engineering Manager


Academy of Motion Picture Arts and Sciences
Science & Technology Council
1313 Vine Street • Hollywood, CA 90028


323.817.4170 • aforsythe@oscars.org<mailto:aforsythe@oscars.org>

**Comment by KelSolaar** [comment]
> For the sake of clarity there should be a config for each ACES release.

Yes I agree, I was thinking exactly about that after writing my initial comment.

**Comment by hpd** [comment]
I'll remove this specific pull request and re-submit one that doesn't eliminate the 1.0.1 config...

**Comment by KelSolaar** [comment]
@hpd : It was dropped because of the space taken by the LUTs right?

**Comment by hpd** [comment]
It was more a mistake on my part to eliminate the 1.0.1 config in the 1.0.2 pull request. Closing this now.

**Pull request closed without merging**
